apiVersion: v1
kind: ConfigMap
metadata:
  name: fyp-config
data:
  DB_DRIVER: "ODBC Driver 17 for SQL Server"
  DB_SERVER: "sa,1433"
  DB_NAME: "fyp"

  DB_DATABASE: "patient_service_dev"
  DB_DATABASE_PORT: "1433"
  RABBITMQ_HOST: "192.168.188.184"
  RABBITMQ_PORT: "5672"
